zookzook/elixir-mongodb-driver

README.md

I was having trouble figuring out how to specify a username/pwd, and finally found an example in the connection_test.exs file. I figured it would be useful to add this to the main README.

Update README.md With Username/PWD Example

---

lib/mongo/mongo_db_connection.ex

This may be the tiniest pull request ever, but I was a bit annoyed seeing the `"My killer app"` string when establishing the connection to MongoDB (I want to use my own funny sentence :wink:). Even when correctly configuring the documented `:appname` option it kept showing.
It turns out the issue was a simply a typo in `Mongo.MongoDBConnection.hand_shake/2` function.
I couldn't find any test covering this configuration option, so this pull request is being offered without the test coverage. If you do have any test coverage for that, please give some directions and I'll add the tests.

Fixes :appname option (typo)

---

lib/mongo.ex

Just trying to squash some dialyzer complaints I get wrapping this module (I am using https://github.com/JakeBecker/elixir-ls and my editor is so angry)
it also doesn't like the bangifed function cause of their potential for no local return

Mongo: generalize inconsistent typespecs

---

README.md

The readme includes bulk write examples but not examples for a
single insert of a document. Add a couple of simple examples
copied from insert_one/insert_many documentation.

Add simple insert examples to the readme

---

lib/mongo.ex
lib/mongo/stream.ex
test/mongo/cursor_test.exs

This PR fixes a minor oversight in the `Mongo.Stream` module. When streaming a cursor, `next_fun` would halt streaming if a batch of documents came up empty for a live cursor, overlooking whether the cursor was marked tailable. This causes tailable cursors to halt immediately after initial exhaustion of documents.
This behavior has been fixed, including a test to ensure tailable cursors with awaitData continue to behave in the appropriate manner.
This required including the originating command used to create a `Mongo.Stream` struct, called `cmd`. This keyword list is passed on to the internal `state` record of the module's `Enumerable` implementation, so that the tailability of the cursor is known when deciding how to handle an empty batch of documents.

Add proper support for tailable cursors and awaitData

---

lib/mongo/auth/scram.ex

Remove the "done" parameter when pattern matching the function that verifies the server signature.
Resolves #78

Update SCRAM auth procedure

---

lib/mongo/grid_fs/bucket.ex
mix.exs

Fixes these warnings:
```
warning: redefining @doc attribute previously set at line 124.
Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head:
@doc """
new docs
"""
def find_one(...)
lib/mongo/grid_fs/bucket.ex:132: Mongo.GridFs.Bucket.find_one/2
warning: :crypto.crypto_one_time/5 defined in application :crypto is used by the current application but the current application does not depend on :crypto. To fix this, you must do one of:
1. If :crypto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
2. If :crypto is a dependency, make sure it is listed under "def deps" in your mix.exs
3. In case you don't want to add a requirement to :crypto, you …
```

Fix build warnings

---

lib/mongo.ex

Resolves https://github.com/zookzook/elixir-mongodb-driver/issues/89
and https://github.com/zookzook/elixir-mongodb-driver/issues/88

Update specs for Mongo.find/4 with error tuple

---

lib/mongo/auth/scram.ex
lib/mongo/pbkdf2.ex

Since Erlang 24 deprecates `crypto:hmac/3` I guess it's time to replace it with the new api.
Added `bxor/2` as a bonus.

Replace deprecated functions

---

lib/mongo/mongo_db_connection.ex
lib/mongo/url_parser.ex
test/mongo/url_parser_test.exs

Since mongo version 4.2 it is possible to enable secure connections
using a new flag "tls". Added support for the flag treating it similar
to the existing "ssl" flag.

Add support for tls setting in connection string

---

lib/mongo.ex
lib/mongo/topology.ex

to replace the default timeout of the gen server call.
When the connection pool is exhausted then the `checkout_session` call puts the caller into a queue and wait's for the next possible connection. The default timeout of the gen server call times out after 5_000 ms, which is too early. So by adding a new options :checkout_session it is possible to specify larger values. Even more, the default timeout value of the gen server call is set to 60_000.

#97: added new option :checkout_timeout 

---

lib/mongo/url_parser.ex
test/mongo/url_parser_test.exs

I've had problems when using srv links and url query params in mongodb driver. This PR fixed the issue for me, maybe it'll help someone else too.

Add back original query options for srv links

---

lib/bson/types.ex
test/bson_test.exs

On current master if BSON.Regex is created without explicitly passed `options` encoding of it will fail with an error message:
```
1st argument: not an iodata term
```
because `nil` is not a valid iodata, and by default `options` is initialized to `nil`. This PR changes `options` to be by default initialized to `''` which seems to be sane default value that preserves correct behavior of BSON.Regex.

Fix for serializing BSON Regex without options

---

lib/bson/encoder.ex

Original implementation for the encoder seemed to work if `Mongo.Encoder` encoded each value into the same "type" most likely `Map` -> `Document`. I wanted to encode a `Map` as a `String` and that required this change to work.

Allow encoding values into different types

---

lib/mongo/mongo_db_connection.ex

Without that `:ok` it seems that `db_connection` process is dying on disconnect: https://hexdocs.pm/db_connection/DBConnection.html

More graceful handling of disconnects

---

CHANGELOG.md
README.md
lib/mongo.ex
lib/mongo/bulk_write.ex
lib/mongo/change_stream.ex
lib/mongo/repo.ex
lib/mongo/session.ex
lib/mongo/stream.ex
lib/mongo/topology.ex
test/collections/simple_test.exs
test/mongo/change_stream_test.exs
test/mongo/encoder_test.exs
test/mongo/not_writable_primary_test.exs
test/mongo/repo_test.exs
test/mongo/transaction_retries_test.exs
test/mongo_test.exs
test/support/collection_case.ex

The goal is to use nested transaction function calls like this:
```elixir
def test_transaction(conn) do
Mongo.transaction(conn, fn ->
Mongo.insert_one(:mongo, "dogs", %{name: "Tom", age: 13})
test_insert_1(conn)
test_insert_2(conn)
end)
end
def test_insert_1(conn) do
Mongo.insert_one(conn, "dogs", %{name: "Greta", age: 11})
end
def test_insert_2(conn) do
Mongo.transaction(conn, fn ->
Mongo.insert_one(:mongo, "dogs", %{name: "Oskar", age: 13})
:error
end)
end
```
All insert commands should participate the current transaction in call `test_transaction/1`.

Refactor transaction api

---

lib/mongo/repo.ex
test/mongo/repo_test.exs

When using the functions `Repo.update/1`, `Repo.insert_or_update/1` and `Repo.insert_or_update!/1` to update a document without changing any attributes an exception is raised.
```elixir
post = MyRepo.get_by(Post, %{})
MyRepo.update(post)
** (CaseClauseError) no case clause matching: {:ok, %Mongo.UpdateResult{acknowledged: true, matched_count: 1, modified_count: 0, upserted_ids: []}}
(mongo_test 0.0.1) lib/repo.ex:2: MyRepo.update/1
```
Not sure if this behavior was intentional, since the error doesn't happen in `Repo.update!/1`
I initially thought that validating if the modified_count was less than or equal to 1, but I don't believe it's something that makes any difference.
What do you think about this approach?

Fix CaseClauseError when update a document without any change

---

.github/workflows/mongodb_driver.yml

I tried to make a test with mongodb 4.0 on the PR [!145](https://github.com/zookzook/elixir-mongodb-driver/pull/145) but every test was timing out and I couldn't cancel the workflow job.
To prevent something like this from happening again, I propose to add this execution timeout.
Based on he previous duration I think 5 minutes is enough to run each normal job. 
Github docs -> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

Adds a default timeout of 5 min for github actions

---

lib/mongo/collection.ex
lib/mongo/repo.ex
test/collections/simple_test.exs

Save custom attribute names in DB
**Struct**
```elixir
%Collections.SimpleTest.Card{
label: %Collections.SimpleTest.Label{color: :red, name: "warning"}, 
_id: #BSON.ObjectId<634b114298234fa6c2cb7e9d>,
created: ~U[2022-10-15 20:00:02.686000Z], 
intro: "new intro",
modified: ~U[2022-10-15 20:00:02.686000Z],
title: "new title"
}
```
**Map**
```elixir
%{
l: %{name: "warning", c: :red},
title: "new title",
_id: #BSON.ObjectId<634b114298234fa6c2cb7e9d>,
created: ~U[2022-10-15 20:00:02.686000Z],
i: "new intro",
modified: ~U[2022-10-15 20:00:02.686000Z]
}
```
**MongodDB Compass** preview

Add :name option to attribute, embeds_one and embeds_many

---

lib/mongo/migration.ex

_**First: sorry if my changes don't follow best practices or are wrong in some way. I discovered these issues while building my first ever elixir application, so I'm brand new to the language 😄**_
This PR contains two changes to the new migration feature. I noticed that one of my migrations was failing to run but I got no errors and the rest of the migrations continued as if nothing was wrong.
I expected there to be error output when my migration failed, and I expected a failed migration to halt further migrations. This is because all migrations should run in order as there could be a dependency on a previous migration running successfully.
The changes I made to support these expectations:
1. [Fix] The pattern match of the `Mongo.find_one` on `run_down` was expecting an atom key when it …

Fix mongo.drop task and add error handling

---

lib/mongo/migration.ex

I noticed that one of my migrations was failing, but future migrations were still being run. It turns out that they were being run out of order. 
It looks like the `File.ls` uses erlang's `:file.dir_list` which does not return files in sorted order:
> The names are not sorted.
_https://www.erlang.org/doc/man/file.html#list_dir-1_
I just pass the returned list of files through `Enum.sort`

Sort migration files before execution

---

.formatter.exs
test/collections/simple_test.exs

fixes https://github.com/zookzook/elixir-mongodb-driver/issues/159
This PR also adds `embeds_one: :*` to the locals_without_parens list and formats the one usage of it.

export locals_without_parens in formatter

---

lib/mongo.ex
lib/mongo/error.ex

Fixes a couple of typespecs which can make dialyzer fail in projects using this library.
Specifically, the `@type result(t)` can also be `{:error, Mongo.WriteError.t()}` as returned, for example, when inserting a document with an already existing `_id`:
```
iex(4)> {:ok, pid} = Mongo.start_link([hostname: "192.168.56.105", database: "test"])
{:ok, #PID<0.290.0>}
iex(5)> Mongo.insert_one(pid, "prova", %{_id: "foo"})                                
{:ok, %Mongo.InsertOneResult{acknowledged: true, inserted_id: "foo"}}
iex(6)> Mongo.insert_one(pid, "prova", %{_id: "foo"})
{:error,
%Mongo.WriteError{
n: 0,
ok: 1.0,
write_errors: [
%{
"code" => 11000,
"errmsg" => "E11000 duplicate key error collection: test.prova index: _id_ dup key: { _id: \"foo\" }",
"index" => 0,
"keyPattern" => %{"_id" => …
```

Fix some typespecs

---

lib/mongo/repo.ex

There were some functions in the Repo module that did not accepts options. Some of those options (such as :database) are important to be able to pass through to the underlying Mongo functions.
I'm not sure if this is the right way to implement this. I'm fairly new to behaviors so I'm not sure if changing the arity of those functions is a breaking change. Any suggestions would be welcome. It's a small thing, so I'm also happy to start over if this needs to be done completely differently.

Adds options argument to some functions

---

lib/mongo/migration.ex
test/mongo/migration_test.exs

This is a way we can support dynamic multitenancy. If you pass in the :database option into the `migrate/1` function, it will forward it onto each migrations `up` function, but we also need it to use the database option for each of the calls to the migration collection, so that each tenant's migration states are kept separate.
Perhaps there's a better more explicit way of doing this. Super open to other suggestions :)

Forwards the :database option to the migration collection calls

---

lib/bson/types.ex
test/bson/types_test.exs

I'm not sure if this is desired, but we've found this to be incredibly helpful, especially when we're translating object ids to JSON, or logging them out in a string.

implements String.Chars for BSON.ObjectId

---

lib/mongo/error.ex
test/mongo/errors_test.exs

Problem: Since 5.0 mongo supports extended error messages for error 121 (document failed validation), but driver cuts it off.
Solution: add it to Mongo.Error if it exists
PS: I suspect it will be useful in other cases too

Add support of errInfo

---

lib/mongo.ex
test/mongo_test.exs

I noticed that arrayFilters was supported in the `update_one` and `update_many` functions, but not in the `find_one_and_update`.

feat: Find one and update array filters

---

README.md

Clarifying the implications of documents always being decoded as maps, explaining when to represent documents as lists of tuples, explaining why decoding never creates atoms, and noting that BSON symbols are deprecated.
_Based on discussion #204_

Update note on data representation

---

lib/mongo/grid_fs/upload.ex
lib/mongo/grid_fs/upload_stream.ex
test/mongo/grid_fs/upload_test.exs

For: [216 - In GridFs, allow assigning a custom _id to documents in files collection](https://github.com/zookzook/elixir-mongodb-driver/issues/216)
Allowing custom ids means the _id could be a binary, which Mongo supports.

FIX-216: Allow passing optional _id while uploading to gridfs files

---

lib/mongo/mongo_db_connection.ex

Our server connects to MongoDB via an IP address. We created an SSL certificate and added the ip address in. However the MongoDB driver fails to verify the host name.
After digging deep into the code, I found that the driver sets `server_name_indication` for IP addresses, which leads to wrong ReferenceID being tagged as `:dns_id`. According to https://github.com/erlang/otp/blob/OTP-27.0/lib/public_key/src/public_key.erl#L2771, this will not match any IP address in the certificate.
This PR added IP address detection and skip setting SNI when IP address is presented.
**Experiment 1:**
```elixir
defmodule SSLConn do
def pkix_verify_hostname(fqdn, host) do
IO.inspect("#{inspect(fqdn)}, #{inspect(host)}")
:default
end
def connect() do
host = ~c"127.0.0.1"
port = 27018
{:ok, socket} = …
```

Fixed SSL IP address verification

---

lib/mongo.ex
test/mongo_test.exs

Changes:
- prevent endless recursion when supplied empty list
- make options list optional
- add more documentation + tests
Fixes #243

fix(update/4): improve Mongo.update/4 function

---

lib/mongo.ex

In reference to this issue: https://github.com/zookzook/elixir-mongodb-driver/issues/249
Very minor non breaking changes on typespecs

Remove unused typespecs, fix `find_one_and_update` typespec

---

README.md
lib/mongo/repo.ex
test/mongo/repo_test.exs

To make it more convenient to add to an application's supervision tree, similar to how `Ecto.Repo`-based modules are typically added to the supervision tree.

Implement Mongo.Repo.child_spec/1

---

lib/bson/decoder.ex

When running against our Mongo instance we got the following error:
```
%FunctionClauseError{module: BSON.Decoder, function: :type, arity: 2, kind: nil, args: nil, clauses: nil}
```
Turns out that, at least for our Mongo installation, this case is used for NaN. I have validated that the value is NaN in Mongo Compass and adding this case results in the document being deserialised to the same values as in Compass.

Add missing decoder case for NaN

---

lib/mongo.ex
lib/mongo/session.ex
lib/mongo/stream.ex

Our team thought the docs could be more explicit about how to handle sessions when consuming Mongo.Streams. Let me know if these updates are clear, I'm happy to make any changes or improvements if needed.

Add notes regarding closing sessions when working with streams

---

lib/mongo/url_parser.ex

Changes:
- use :inet_res.lookup instead of :inet_res.getbyname to prevent failures on missing txt records when resolving the connection string
The following code fixes issue #260

fix(master): ensure url_parser does not fail on missing txt record

---

mix.exs

I've been keeping an override in a project to be able to upgrade `decimal`. Other dependencies related to Phoenix specify `~> 2.0`, but recently reading the Elixir forum I realized we can do better:
https://elixirforum.com/t/conflicting-dependencies-and-use-of-the-operator/68207/14?u=rhcarvalho

Allow newer versions of decimal 2.x

---

lib/bson/types.ex
test/bson/types_test.exs

Python and node.js mongodb libraries have helper functions to extract timestamp from `ObjectId`. The PR adds those missing helper functions.

Add function `BSON.ObjectId.get_timestamp/1` and `BSON.ObjectId.get_timestamp!/1`

---

lib/mongo/topology.ex
lib/mongo/topology_description.ex
lib/mongo/url_parser.ex
test/mongo/topology_description_test.exs
test/mongo/url_parser_test.exs

Support `directConnection` option in the MongoDB connection string options. Please review it. Thank you!
ref: https://www.mongodb.com/docs/manual/reference/connection-string-options/#mongodb-urioption-urioption.directConnection

Add support for directConnection setting in connection string.

---

lib/mongo/read_preference.ex
lib/mongo/server_description.ex
lib/mongo/topology_description.ex
test/mongo/topology_description_test.exs
test/support/topology_test_data.ex

We found the issue with querying the data when we use `directConnection=true` and the cluster is a replica set. We got this error by using the following steps.
```elixir
iex> {:ok, top} = Mongo.start_link(url: "mongodb://localhost:27018/test?directConnection=true&readPreference=secondary&authSource=admin&maxPoolSize=1")
{:ok, #PID<0.230.0>}
iex> Mongo.aggregate(top, "test", [], [])
{:error,
%Mongo.Error{
message: "not primary and secondaryOk=false",
code: 13435,
host: nil,
fail_command: false,
error_labels: [],
resumable: true,
retryable_reads: true,
retryable_writes: true,
not_writable_primary_or_recovering: true,
error_info: nil
}}
```
Then I traced the Python MongoDB driver source code and found it set read_preference to `primaryPreferred` when topology single with replica set. Here is …

Set read_preference to primaryPreferred when topology single with replica set.

---

lib/mongo/id_server.ex

Keep the same behaviour as with earlier elixir versions.
Fix:
```
warning: Range.new/2 and first..last default to a step of -1 when last < first. Use Range.new(first, last, -1) or first..last//-1, or pass 1 if that was your intention
(mongodb_driver 1.5.2) lib/mongo/id_server.ex:43: Mongo.IdServer.handle_info/2
(stdlib 6.2.2) gen_server.erl:2345: :gen_server.try_handle_info/3
(stdlib 6.2.2) gen_server.erl:2433: :gen_server.handle_msg/6
(stdlib 6.2.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```
Issue #271 
Be aware I wasn't able to run tests locally. I have MongoDB running locally, but the test suite doesn't connect to it, and I can't find instructions on how to do that.

Force increasing Range
